# Generated by Django 4.2.7 on 2023-12-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='noofitems',
            new_name='no_of_items',
        ),
    ]
